services:
  backend:
    image: davidzajac1/zillacode-backend:latest
    ports:
      - 5001:5001
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - spark-net
      - scala-spark-net
      - db-lambda-net
    environment:
      - FLASK_DEBUG=1
      - TESTING=1
      - FLASK_ENV=local
  frontend:
    image: davidzajac1/zillacode-frontend:latest
    ports:
      - 5173:5173
    networks:
      - spark-net
      - scala-spark-net
      - db-lambda-net
  spark:
    image: davidzajac1/zillacode-spark:latest
    ports:
      - 8081:8080
    networks:
      spark-net:
        ipv4_address: 10.5.0.6
  scala-spark:
    image: davidzajac1/zillacode-scala-spark:latest
    ports:
      - 8082:8080
    networks:
      scala-spark-net:
        ipv4_address: 10.4.0.6
  db-lambda:
    image: davidzajac1/zillacode-db-service:latest
    ports:
      - 8083:8080
    networks:
      db-lambda-net:
        ipv4_address: 10.8.0.6

networks:
  spark-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
  scala-spark-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.0/16
          gateway: 10.4.0.1
  db-lambda-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1
